language: node_js
node_js: 10
cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: true
    addons:
      apt:
        packages:
          - rpm
          - gcc-multilib
          - g++-multilib
          - snapd
    before_install:
      - sudo snap install snapcraft --classic
    deploy:
      - provider: snap
        snap: dist/*.snap
        channel: beta
        skip_cleanup: true
        on:
          branch: develop
      - provider: snap
        snap: dist/*.snap
        channel: stable
        skip_cleanup: true
        on:
          branch: master
  - os: osx
    osx_image: xcode11.2

branches:
  only:
    - master
    - develop
    - /^hotfix\/.*$/
    - /^release\/.*$/

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - yarn
  - yarn test

script:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then export CSC_IDENTITY_AUTO_DISCOVERY=false; fi
  - NODE_ENV=production yarn release
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      xcrun altool --validate-app --file dist/*-mas.pkg --username "$APPLEID" --password "APPLEIDPASS"
    fi
